In [1]:
from keras.layers import Conv1D, Input
import numpy as np
np.random.seed(1)

Using TensorFlow backend.


In [135]:
inp = np.random.randint(5, size = (1,10, 4))
inp


array([[[3, 4, 0, 1],
        [3, 0, 0, 1],
        [4, 4, 1, 2],
        [4, 2, 4, 3],
        [4, 2, 4, 2],
        [4, 1, 1, 0],
        [1, 1, 1, 1],
        [0, 4, 1, 0],
        [0, 3, 2, 1],
        [0, 3, 1, 1]]])

In [6]:
from keras.models import Model

In [139]:
inputs = Input(shape=(10,4))
x = Conv1D(2,2,name='yos')(inputs)
model = Model(inputs = inputs, outputs = x)

In [140]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_21 (InputLayer)        (None, 10, 4)             0         
_________________________________________________________________
yos (Conv1D)                 (None, 9, 2)              18        
Total params: 18
Trainable params: 18
Non-trainable params: 0
_________________________________________________________________


In [141]:
def_weight = model.get_layer('yos').get_weights()

In [142]:
print(def_weight[0].shape)

(2, 4, 2)


In [145]:
weights = []
x = np.ones((2,4,2))
b = np.zeros((2,))
weights.append(x)
weights.append(b)


In [146]:
model.get_layer('yos').set_weights(weights)

In [147]:
out = model.predict(inp)

In [150]:
out

array([[[12., 12.],
        [15., 15.],
        [24., 24.],
        [25., 25.],
        [18., 18.],
        [10., 10.],
        [ 9.,  9.],
        [11., 11.],
        [11., 11.]]], dtype=float32)

In [151]:
inp

array([[[3, 4, 0, 1],
        [3, 0, 0, 1],
        [4, 4, 1, 2],
        [4, 2, 4, 3],
        [4, 2, 4, 2],
        [4, 1, 1, 0],
        [1, 1, 1, 1],
        [0, 4, 1, 0],
        [0, 3, 2, 1],
        [0, 3, 1, 1]]])

In [4]:
from keras.layers import LSTM, BatchNormalization, Activation, Dropout



In [9]:
inp = Input(shape=(1292, 128))

x = Conv1D(filters=128, kernel_size=4)(inp)
x = BatchNormalization()(x)
x = Activation('relu')(x)
x = MaxPooling1D()(x)
x = Dropout(0.5)(x)

x = Conv1D(filters=256, kernel_size=4)(x)
x = BatchNormalization()(x)
x = Activation('relu')(x)
x = MaxPooling1D()(x)
x = Dropout(0.5)(x)

x = Cu(256, return_sequences=True)(x)
model = Model(inputs=inp, outputs=x)
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         (None, 1292, 128)         0         
_________________________________________________________________
conv1d_8 (Conv1D)            (None, 1288, 128)         82048     
_________________________________________________________________
batch_normalization_8 (Batch (None, 1288, 128)         512       
_________________________________________________________________
max_pooling1d_7 (MaxPooling1 (None, 644, 128)          0         
_________________________________________________________________
dropout_7 (Dropout)          (None, 644, 128)          0         
_________________________________________________________________
conv1d_9 (Conv1D)            (None, 642, 256)          98560     
_________________________________________________________________
batch_normalization_9 (Batch (None, 642, 256)          1024      
__________